# Generated by Django 3.0.5 on 2020-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DontFretShop', '0002_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='UNBRANDED', max_length=250),
        ),
    ]
