# Generated by Django 3.0.5 on 2020-05-13 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200512_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cardCCV',
            field=models.CharField(default='000', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='CCV No (Back Of Card)'),
        ),
        migrations.AddField(
            model_name='order',
            name='cardExpiryDate',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Card Expiry Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='cardNo',
            field=models.CharField(default='0000000000000000', max_length=16, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Card No.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='emailAddress',
            field=models.EmailField(max_length=250, verbose_name='Email Address'),
        ),
    ]
