# Generated by Django 3.0.5 on 2020-05-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200513_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
    ]
