# Generated by Django 3.0.5 on 2020-05-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_is_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_refundable',
        ),
        migrations.AlterField(
            model_name='order',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
